# Generated by Django 5.2 on 2025-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('image_link', models.URLField()),
                ('availability', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=255)),
                ('gtin', models.CharField(max_length=255)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_product_category', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_image_links', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('product_length', models.FloatField(blank=True, null=True)),
                ('product_width', models.FloatField(blank=True, null=True)),
                ('product_height', models.FloatField(blank=True, null=True)),
                ('product_weight', models.FloatField(blank=True, null=True)),
                ('lifestyle_image_link', models.URLField(blank=True, null=True)),
                ('max_handling_time', models.IntegerField(blank=True, null=True)),
                ('is_bundle', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
